"""Added Create/Update timestamps and some constraints

Revision ID: 175617720186
Revises: 
Create Date: 2015-01-30 01:33:19.307703

"""

# revision identifiers, used by Alembic.
revision = '175617720186'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import text
conn = op.get_bind()

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('translation', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('word', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('word', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False))
    op.alter_column('word', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('word', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('word', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
    conn.execute(text("update translation set word_a_id = word_b_id, word_b_id = word_a_id where word_a_id > word_b_id"))
    op.create_unique_constraint("translation_word_a_id_word_b_id_key", "translation", ["word_a_id", "word_b_id"])
    op.create_check_constraint("ordered_ids", "translation", "word_a_id < word_b_id")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('word', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('word', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('word', 'updated')
    op.drop_column('word', 'created')
    op.drop_column('translation', 'updated')
    op.drop_column('translation', 'created')
    ### end Alembic commands ###
    op.drop_constraint("translation_word_a_id_word_b_id_key", "translation")
    op.drop_constraint("ordered_ids", "translation")

