"""worldistitem foreign key reversal

Revision ID: 370b55ad6714
Revises: 3b4d375b597c
Create Date: 2015-02-01 22:05:19.670000

"""

# revision identifiers, used by Alembic.
revision = '370b55ad6714'
down_revision = '3b4d375b597c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'wordlistitem_wordlist_id_fkey', 'wordlistitem', type_='foreignkey')
    op.drop_constraint(u'wordlistitem_translation_id_fkey', 'wordlistitem', type_='foreignkey')
    op.create_foreign_key(None, 'wordlistitem', 'wordlist', ['wordlist_id'], ['id'])
    op.create_foreign_key(None, 'wordlistitem', 'translation', ['translation_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wordlistitem', type_='foreignkey')
    op.drop_constraint(None, 'wordlistitem', type_='foreignkey')
    op.create_foreign_key(u'wordlistitem_translation_id_fkey', 'wordlistitem', 'wordlist', ['translation_id'], ['id'])
    op.create_foreign_key(u'wordlistitem_wordlist_id_fkey', 'wordlistitem', 'translation', ['wordlist_id'], ['id'])
    ### end Alembic commands ###
