"""empty message

Revision ID: 3b4d375b597c
Revises: 175617720186
Create Date: 2015-01-30 15:48:21.710113

"""

# revision identifiers, used by Alembic.
revision = '3b4d375b597c'
down_revision = '175617720186'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False),
            sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
            )
    op.create_table('wordlistitem',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False),
            sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False),
            sa.Column('wordlist_id', sa.Integer(), nullable=True),
            sa.Column('translation_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['translation_id'], ['wordlist.id'], ),
            sa.ForeignKeyConstraint(['wordlist_id'], ['translation.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('wordlist_id', 'translation_id')
            )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordlistitem')
    op.drop_table('wordlist')
    ### end Alembic commands ###
